channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=23.3.1
- pip:
  - mlflow==2.11.3
  - keras==3.1.1
  - numpy==1.26.4
  - protobuf==3.20.3
  - tensorflow-intel==2.16.1
name: mlflow-env
